name: bikemi
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.2=py39h6e9494a_1
  - argon2-cffi=20.1.0=py39h89e85a6_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.1=pyhd8ed1ab_0
  - ca-certificates=2021.5.30=h033912b_0
  - certifi=2021.5.30=py39h6e9494a_0
  - cffi=1.14.6=py39hb71fe58_0
  - cycler=0.10.0=py_2
  - debugpy=1.3.0=py39h9fcab8e_0
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h4cff582_1
  - importlib-metadata=4.6.1=py39h6e9494a_0
  - ipykernel=6.0.2=py39h71a6800_0
  - ipython=7.25.0=py39h71a6800_1
  - ipython_genutils=0.2.0=py_1
  - jbig=2.1=h0d85af4_2003
  - jedi=0.18.0=py39h6e9494a_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=hbcb3906_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py39h6e9494a_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - kiwisolver=1.3.1=py39hf018cea_1
  - krb5=1.19.1=hcfbf3a7_0
  - lcms2=2.12=h577c468_0
  - lerc=2.2.1=h046ec9c_0
  - libblas=3.9.0=9_openblas
  - libcblas=3.9.0=9_openblas
  - libcxx=12.0.1=habf9029_0
  - libdeflate=1.7=h35c211d_5
  - libedit=3.1.20191231=h0678c8f_2
  - libffi=3.3=h046ec9c_2
  - libgfortran=5.0.0=9_3_0_h6c81a4c_22
  - libgfortran5=9.3.0=h6c81a4c_22
  - liblapack=3.9.0=9_openblas
  - libopenblas=0.3.15=openmp_h5e1b9a4_1
  - libpng=1.6.37=h7cec526_2
  - libpq=13.3=hea3049e_0
  - libsodium=1.0.18=hbcb3906_1
  - libtiff=4.3.0=h1167814_1
  - libwebp-base=1.2.0=h0d85af4_2
  - llvm-openmp=12.0.1=hda6cdc1_0
  - lz4-c=1.9.3=h046ec9c_0
  - markupsafe=2.0.1=py39h89e85a6_0
  - matplotlib=3.4.2=py39h6e9494a_0
  - matplotlib-base=3.4.2=py39hb07454d_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py39h89e85a6_1004
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py39h6e9494a_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=h2e338ed_4
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.0=pyha770c72_0
  - numpy=1.21.0=py39h7eed0ac_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=h6e7aa92_1
  - openssl=1.1.1k=h0d85af4_0
  - packaging=21.0=pyhd8ed1ab_0
  - pandas=1.3.0=py39h4d6be9b_0
  - pandoc=2.14.0.3=h0d85af4_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - patsy=0.5.1=py_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.3.1=py39he9bb72f_0
  - pip=21.1.3=pyhd8ed1ab_0
  - plotly=5.1.0=pyhd8ed1ab_1
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - psycopg2=2.9.1=py39h9d1abf3_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py39h89e85a6_2
  - python=3.9.6=hd187cdc_1_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.9=2_cp39
  - pytz=2021.1=pyhd8ed1ab_0
  - pyzmq=22.1.0=py39h7fec2f1_0
  - readline=8.1=h05e3726_0
  - scipy=1.7.0=py39h056f1c0_0
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=49.6.0=py39h6e9494a_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h23a322b_0
  - statsmodels=0.12.2=py39h329c335_0
  - tenacity=8.0.1=pyhd8ed1ab_0
  - terminado=0.10.1=py39h6e9494a_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=h0419947_1
  - tornado=6.1=py39h89e85a6_1
  - traitlets=5.0.5=py_0
  - tzdata=2021a=he74cb21_1
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - xz=5.2.5=haf1e3a3_1
  - zeromq=4.3.4=h1c7c35f_0
  - zipp=3.5.0=pyhd8ed1ab_0
  - zlib=1.2.11=h7795811_1010
  - zstd=1.5.0=h582d3a0_0
prefix: /Users/luca/.pyenv/versions/miniconda3-latest/envs/bikemi
